# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows I see
workflows:
  sonarcloud-workflow:
    jobs:
      - sonarcloud/scan:
          organization: "caroline-amy"
          project-key: "caroline-amy_APDS7311_group12"
