version: 2.1

jobs:
  sonarcloud-scan:
    docker:
      - image: cimg/openjdk:17.0  # Ensure Java 17 is used
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Clear APT Cache
          command: |
            sudo rm -rf /var/lib/apt/lists/*
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
      - run:
          name: Install Sonar Scanner with Embedded JRE 17
          command: |
            curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner-cli.zip
            mv sonar-scanner-5.0.1.3006-linux sonar-scanner
            echo 'export PATH=$PATH:$(pwd)/sonar-scanner/bin' >> $BASH_ENV
      - run:
          name: Run SonarCloud Analysis
          command: |
            source $BASH_ENV
            java -version  # Confirm Java 17
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="caroline-amy_APDS7311_group12" \
              -Dsonar.organization="caroline-amy" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  version: 2
  sonarcloud-workflow:
    jobs:
      - sonarcloud-scan
