version: 2.1

jobs:
  sonarcloud-scan:
    docker:
      - image: jruby:9.3
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y unzip
      - run:
          name: Install Sonar Scanner
          command: |
            curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip
            mv sonar-scanner-4.6.2.2472-linux sonar-scanner
            echo 'export PATH=$PATH:$(pwd)/sonar-scanner/bin' >> $BASH_ENV
      - run:
          name: Run SonarCloud Analysis
          command: |
            source $BASH_ENV
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="caroline-amy_APDS7311_group12" \
              -Dsonar.organization="caroline-amy" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

workflows:
  version: 2
  sonarcloud-workflow:
    jobs:
      - sonarcloud-scan
